scalar Date

input CreateUserInput {
  nome: String
  email: String
  password: String
  identificacao: String
}

enum TipoUser {
  CLIENTE_PJ
  CLIENTE_FISICO
  ADMIN
}

type User {
  nome: String
  email: String
  password: String
  identificacao: String

  tipoUser: TipoUser

  id: ID
  idb: String
  createdAt: Date
  updated: Date
  ultimoLogin: Date
}

# ##############################################
# PONTOS DE ENTRADAS :: CONSULTAS & MUTACOES
# ##############################################

type Query {
  helloUser: String
  getUsers: [User]!
}

type Mutation {
  createUser(nome: String, email: String, password: String, identificacao: String): User
}
